### ISSUE TITLE
(feat)Develop basic front end

### ISSUE THREAD

**Issue by csavage1994** [silverSquirrels/silverSquirrels#7]
Basic reqs:
Angular?
Set up home page, sign up, and signed in page (structure not style/functionality)
-Home page should have a link to sign up and a form to sign in
-Sign up should be a simple form
-Signed in should just be a template for now?

**Comment by csavage1994** [comment]
-Pair?

**Comment by mfrazie2** [comment]
Authentication for users - sign in through Google/Facebook/Twitter/etc
